version: "3"

services:
  djangoapp_front:
    image: emrahburak/microservice-kandilli-front-prod:0.0.1
    volumes:
      - djangoapp_front_vol:/www

    env_file:
      - ./config/db/.env
    networks:
      - nginx_front_nt
      - postgresql_nt
    depends_on:
      - databasepostgresql

  djangoapp_back:
    image: emrahburak/microservice-kandilli-back-prod:0.1.0
    volumes:
      - djangoapp_back_vol:/www

    env_file:
      - ./config/db_remote/.env
    networks:
      - nginx_back_nt
      - postgresql_nt
    depends_on:
      - databasepostgresql

        

  nginx_front:
    image: emrahburak/nginx-health-kandilli-curl:latest 
    ports:
      - 8000:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - djangoapp_front
    networks:
      - nginx_front_nt
    healthcheck:
      test: curl -sS http://0.0.0.0/api/kandilli/index/ || exit 1
      # test: curl http://0.0.0.0:8000/api/kandilli/remote/ || exit 1
      interval: 20s
      timeout: 2s
      retries: 2

        
  nginx_back:
    image: emrahburak/nginx-health-kandilli-curl:latest 
    ports:
      - 8001:80
    volumes:
      - ./config/nginx_back/conf.d:/etc/nginx/conf.d
    depends_on:
      - djangoapp_back
    networks:
      - nginx_back_nt
    healthcheck:
      test: curl -sS http://0.0.0.0/api/microservice/kandilli || exit 1
      interval: 1m
      timeout: 30s
      retries: 2

  databasepostgresql:
    image: postgres:latest
      
    env_file:
      - ./config/db/.env
    volumes:
      - databasepostgresql_volume_swarm:/var/lib/postgresql/data
      # - databasepostgresql_volume_remote:/var/lib/postgresql/data
    networks:
      - postgresql_nt



        
networks:
  nginx_front_nt:
    driver: bridge
  nginx_back_nt:
    driver: bridge
  postgresql_nt:
    driver: bridge
    

volumes:
    databasepostgresql_volume_swarm:
    djangoapp_front_vol:
    djangoapp_back_vol:

    # databasepostgresql_volume_remote:
      
  
