version: "3"

services:
  djangoapp:
    image: emrahburak/kandilli-slim-buster:0.0.4
    volumes:
      # - .:/www
      - djangoapp_volume:/www

    env_file:
      - ./config/db/.env
    networks:
      - nginx_network_swarm
      - databasepostgresql_network_swarm
    depends_on:
      - databasepostgresql

  nginx:
    image: emrahburak/nginx-health-kandilli-curl:latest 
    ports:
      - 8000:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - djangoapp
    networks:
      - nginx_network_swarm
    healthcheck:
      test: curl -sS http://0.0.0.0/api/kandilli/remote/ || exit 1

      interval: 1m
      timeout: 30s
      retries: 1
        


  databasepostgresql:
    image: postgres:latest
      
    env_file:
      - ./config/db/.env
    volumes:
      - databasepostgresql_volume_swarm:/var/lib/postgresql/data
    networks:
      - databasepostgresql_network_swarm
        
networks:
  nginx_network_swarm:
    driver: overlay
    # external:
    #   name: nginx_network

  databasepostgresql_network_swarm:
    driver: overlay
    # external:
    #   name: databasepostgresql_network


volumes:
    # databasepostgresql_volume_remote:
    djangoapp_volume:
    databasepostgresql_volume_swarm:
      
  
