# Generated by Django 3.0.7 on 2020-06-07 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kandilli',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateField(blank=True, null=True)),
                ('saat', models.TimeField(blank=True, null=True)),
                ('enlem', models.FloatField(blank=True, null=True)),
                ('boylam', models.FloatField(blank=True, null=True)),
                ('derinlikkm', models.FloatField(blank=True, null=True)),
                ('md', models.FloatField(blank=True, null=True)),
                ('ml', models.FloatField(blank=True, null=True)),
                ('mw', models.FloatField(blank=True, null=True)),
                ('yer', models.CharField(blank=True, max_length=200, null=True)),
                ('cozumniteligi', models.CharField(blank=True, db_column='cozumniteligi', max_length=200, null=True)),
            ],
        ),
    ]
